// Generates dist/tokens.css and src/generated/tokens.ts from src/tokens.json.
// Run via `pnpm --filter @webx-ui/tokens generate` (also part of `build`).
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const source = JSON.parse(readFileSync(resolve(root, 'src/tokens.json'), 'utf8'))

const PREFIX = '--wx-'
const REFERENCE = /^\{([^}]+)\}$/

/** Flattens a nested object into `[dashed.path, value]` pairs. */
function flatten(node, path = []) {
  return Object.entries(node).flatMap(([key, value]) =>
    typeof value === 'object' && value !== null
      ? flatten(value, [...path, key])
      : [[[...path, key].join('.'), String(value)]],
  )
}

function varName(dottedPath) {
  return PREFIX + dottedPath.split('.').join('-')
}

function lookup(dottedPath) {
  return dottedPath.split('.').reduce((node, key) => (node == null ? undefined : node[key]), source)
}

/** `{primitive.color.blue.600}` -> `var(--wx-color-blue-600)`; literals pass through. */
function resolveValue(value, context) {
  const match = REFERENCE.exec(value)
  if (!match) return value
  const target = match[1]
  if (lookup(target) === undefined) {
    throw new Error(`Unknown token reference "{${target}}" in ${context}`)
  }
  return `var(${varName(target.replace(/^primitive\./, ''))})`
}

const primitives = flatten(source.primitive).map(([path, value]) => [varName(path), value])

function semanticVars(theme) {
  return Object.entries(source.semantic[theme]).map(([key, value]) => [
    varName(key),
    resolveValue(value, `semantic.${theme}.${key}`),
  ])
}

const light = semanticVars('light')
const dark = semanticVars('dark')

/** Density overrides are plain var overrides, scoped to a class instead of a theme. */
const compact = Object.entries(source.density.compact).map(([key, value]) => [
  varName(key),
  resolveValue(value, `density.compact.${key}`),
])

const block = (pairs, indent = '  ') =>
  pairs.map(([name, value]) => `${indent}${name}: ${value};`).join('\n')

const css = `/* Generated by packages/tokens/scripts/generate.mjs — do not edit by hand. */
:root {
  color-scheme: light;

  /* primitives */
${block(primitives)}

  /* semantic — light */
${block(light)}
}

[data-theme='dark'] {
  color-scheme: dark;

${block(dark)}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
    color-scheme: dark;

${block(dark, '    ')}
  }
}

/* Denser controls for tables, toolbars and dialogs. Scope it to any subtree. */
.wx-density-compact,
[data-density='compact'] {
${block(compact)}
}
`

const asRecord = (pairs) =>
  `{\n${pairs.map(([name, value]) => `  '${name}': ${JSON.stringify(value)},`).join('\n')}\n}`

const ts = `/* eslint-disable */
/* Generated by packages/tokens/scripts/generate.mjs — do not edit by hand. */

export const tokens = ${JSON.stringify(source, null, 2)} as const

/** CSS custom properties emitted for the light theme (primitives + semantic). */
export const lightVars: Record<string, string> = ${asRecord([...primitives, ...light])}

/** CSS custom properties overridden for the dark theme. */
export const darkVars: Record<string, string> = ${asRecord(dark)}

/** CSS custom properties applied by the .wx-density-compact class. */
export const compactVars: Record<string, string> = ${asRecord(compact)}
`

mkdirSync(resolve(root, 'dist'), { recursive: true })
mkdirSync(resolve(root, 'src/generated'), { recursive: true })
writeFileSync(resolve(root, 'dist/tokens.css'), css)
writeFileSync(resolve(root, 'src/generated/tokens.ts'), ts)

console.log(
  `tokens: ${primitives.length} primitives, ${light.length} semantic, ${compact.length} compact -> dist/tokens.css`,
)
